repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        name: ruff-sort-imports
        args: [--fix, --select, I]
      - id: ruff
        name: ruff-unused-imports
        args: [--fix, --select, F]
      - id: ruff
        name: ruff-bugbear
        args: [--fix, --select, B]
      - id: ruff
        name: ruff-whitespace
        args: [--fix, --select, W]
      - id: ruff-format

  - repo: https://github.com/mwouts/jupytext
    rev: v1.18.1
    hooks:
      - id: jupytext
        args: [--sync, --pipe, "ruff format"]
        additional_dependencies:
          - ruff==0.14.10

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
